### ISSUE TITLE
appimage on kubuntu 21.04

### ISSUE THREAD

**Issue by datamaskinen** [son-link/minimal-podcasts-player#9] opened 2021-04-25 11:31 UTC
It worked to start it the first time then it crashed and now it gives me this output....
Just get that search function going and make a new release ... then this software is right there ... beautiful little thing this is

 ./Minimal_Podcasts_Player-0.2.0-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_Minima4JgQk6/usr/bin/minimal-podcasts-player", line 3, in <module>
    mpp.init()
  File "/tmp/.mount_Minima4JgQk6/usr/conda/lib/python3.8/site-packages/mpp/__init__.py", line 333, in init
    if config['theme'] != 'system':
KeyError: 'theme'

**Comment by son-link** [comment] 2021-04-26 05:16
Duplicate of #3
This issue will be resolved in the next release. I wanted to have it ready earlier, but these last 2 weeks I have had a lot of work and I needed to rest.
For the moment open the file ~/.local/share/mpp/mpp.ini and add these line:
theme = default
Unfortunately the .AppImage doesn't take the theme you are using, so in the next release it will use the default Freeze theme.

**Comment by datamaskinen** [comment] 2021-04-27 12:00
have a rest man ... it is important...

The workaround solves the problem .... nice

**Closed** 2021-04-27 12:02 UTC
Labels: duplicate
